// <auto-generated />
namespace PlasticManufacturer.InfraStructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class muitosparamuitoscustomereendereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(muitosparamuitoscustomereendereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281509388_muitos para muitos customer e endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
