export * from './maritalStatus.service'
export * from './maritalStatus.component'
export * from './maritalStatus.model'
export * from './maritalStatus-guard.service'
export * from './maritalStatus-list.component'